### ISSUE TITLE
Saving to DB Immediately After login

### ISSUE THREAD

**Issue by emilylordahl** [emilylordahl/checkup#13]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "As a user, I want to save my search results to a checkup list so that I can track what appointments I've completed this year."

I am working on the `backbone` branch of my repo.
##### WHAT YOU ARE TRYING TO DO:

I am trying to save the data that is returned after a user logs in.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I have data rendering from my API, but I would like that data to be stored in my checkups DB automatically once a user signs in. I passed a new function called `saveModel` to run after `render` completes, but I'm getting an error that says `saveModel` is undefined.

```
this.saveModel is undefined.
```

The file involved in my is my Login View. Below is the code for the functions in question.

``` js
    fetchAndRenderSession: function() {
        console.log('Rendering session...');
        $.get('/current_user').done(function(user) {
            if (user) {
                $('#session').html(loggedInTemplate(user));
                App.tipCollection.fetch({
                    success: function() {
                        App.tipCollectionView.setCollection(App.tipCollection);
                        App.tipCollectionView.render(this.saveModel, this);
                    }
                });
            } else {
                $('#session').html(loginTemplate());
            }
        }).fail(function(jqXHR) {
            if (jqXHR.status === 404) {
                $('#session').html('404 Not Found');
            }
        });
    },
```

``` js
    saveModel: function() {
        console.log('Saving Model...');
        debugger;
        var tips = App.tipCollection.models;
        tips.forEach(function(tip) {
            var tipModel = {
                tip: tip.tip,
                description: tip.description
            }
            return tipModel;
        });
        tipModel.save(); 
    }
```
## WHAT I'VE TRIED

I tried writing a success callback in `App.tipCollectionView.render(successCallbackHere);` that did what `saveModel` is doing, but the variables did not exist once I was testing my app in the console so I separated out the logic to try and break it down. But now I'm thinking I need to just write a post route for `/checkups` to store this information. 
## QUESTION

Backbone is still a bit confusing to me, so I'm not sure what might be the best path to take next to accomplish saving these checkup models. If I create a new route to post to `/checkups`, I'm not sure how to connect that to the actions that happen when a user logins.

:heart:
A meticulous and troubled student named Emily who is happy to wait until after lunch for help!

**Comment by WilliamfShaw** [comment]
@emilylordahl Ill be up in a second to help out. 

@harimohanraj89 @DrRobotmck @bigtone1284 taken

**Comment by emilylordahl** [comment]
`Checkup.findOrCreate` isn't working but `Checkup.create` is. I'll keep messing around though. Thanks for your help!! @williamfshaw
