### ISSUE TITLE
ToDo.ly Functionality & El Issue

### ISSUE THREAD

**Issue by emilylordahl** [emilylordahl/checkup#18]
## CONTEXT

@DrRobotmck @harimohanraj89 @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "As a user, I want to mark my tips as done so that I can track what checkups I've completed this year."

I am working on the `backbone` branch of my repo.
##### WHAT YOU ARE TRYING TO DO:

I am trying to change the value of `complete` from `false` to `true` when a user clicks a checkbox.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I've been having some issues with setting my `el` in my collection view, which I think is causing this problem. I created a click event in my single tip view to fire a function in the tip model that changes the value of `complete` from `false` to `true`. But when I click the checkbox that should fire that function, my view doesn't know what was clicked.

The files involved are my Single Tip View, Tip Collection View and Tip Model . Below is the code for each.

``` js
App.Views.Tip = Backbone.View.extend({

    url: '/checkups',

    // className: 'checkbox',

    // el: '#tips-container',

    initialize: function() {
        console.log('Created: Single Tip View');
        this.tipsTemplate = Handlebars.compile($('#tips-template').html());
        this.render();
        console.log(this.$el);
    },

    events: {
        'click .checkbox' : 'toggleDone'
    },

    render: function() {
        this.$el.html(this.tipsTemplate(this.model.toJSON()));
        this.saveModel();
    },

    saveModel: function() {
        console.log('Saving Model...');

        $.post('/checkups', {
            tip: this.model.attributes.tip,
            description: this.model.attributes.description
        }).done(this.changeClass.bind(this)); 
    },

    changeClass: function() {
        console.log('Changing class');
        var completeStatus = this.model.get('complete');
        if (completeStatus === true) {
            this.$el.addClass('done')
        } else {
            this.$el.removeClass('done')
        }
        console.log(this.$el);
    },

    toggleDone: function() {
        console.log('You clicked the checkbox!');
        this.model.toggle();
    }

});
```

``` js
App.Views.Tips = Backbone.View.extend({

    el: '#tips-container',

    initialize: function() {
        console.log('Created: Tips Collection View');
        this.listenTo(this.collection, 'reset', this.renderOne);
        this.listenTo(this.collection, 'add', this.renderOne);
        this.render();
    },

    render: function() {
        this.setElement('#tips-container');
        this.collection.each(this.renderOne.bind(this));
    },

    renderOne: function(tip) {
        console.log('Fetching and Rendering...');
        var tipView = new App.Views.Tip({ model: tip });
        this.$el.append(tipView.$el.html());
    },

    setCollection: function(collection) {
        this.collection = collection;
    }
}); 
```

``` js
console.log('Loaded: models/tip.js');

App.Models.Tip = Backbone.Model.extend({
    initialize: function() {
        console.log('Created: Tip Model');
    },

    toggle: function() {
        this.get('complete') ? this.save('complete', false) : this.save('complete', true);
    }
});
```
## WHAT I'VE TRIED

I tried setting an el in the single tip view just to see if the function would fire, and it does, but because my collection has a url of `/search`, which is the route to ping my API at the beginning of the app, that route is hit for however many models are returned times 2.

I tried moving the `toggle` function into the single tip view and just replaced that for `toggleDone`. If I set the `el` to `#tips-container`, and inserted a debugger in the `toggle` function I can manually get the `complete` value from the console and save it as `true` but I don't know how to translate that to my code. Doing it this way does mess up how my content renders so I'm stuck.
## QUESTION

Should I be making a new `put` route to update the values or will `get` and `save` do that same job? I'm not really sure how to move things around to get this toggle complete status to work.

:heart:
Emily

**Comment by DrRobotmck** [comment]
@emilylordahl 
Some questions:
- Does the model exist on the server side that you are attempting to update?
- Does the `el` you are attempting to use exist on the dom?
- Where are requests being submitted to?
- Should your Tip View have a url property?

A tip:
- it might be beneficial to give the model itself a URL to use in order to perform saves/updates that will override the URL property set by your collection.

**Comment by emilylordahl** [comment]
@DrRobotmck

The model does exist on the server side! It's saved to the DB with a default value of false when the user signs in. (I know that because that the default value is always set to false at this point that's going to be messed up every time a user logs in again, but for now I just want to get the toggle functionality working when a user is signed in to a current session).

As of now, the `/search` route is a get route that retrieves all the information from my API and sets the properties based on the response to the models in question.

`/search` would probably not be the right place to update because the `/search` route has pretty specific functionality. I know I need to create a new route to update these values, but I'm not sure where that would fit in to what I have going on in Backbone.

**Comment by emilylordahl** [comment]
Thanks @DrRobotmck!!!
