### ISSUE TITLE
Getting Data Issue

### ISSUE THREAD

**Issue by emilylordahl** [emilylordahl/checkup#3]
## CONTEXT

@williamfshaw @bigtone1284 @p4w5
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "As a user, I want to sign up for this app so that I can search by my age,  gender and other parameters to receive recommendations on what doctors I should be visiting this year to maintain my health."

I am working on the `routes` branch of my repository.
##### WHAT YOU ARE TRYING TO DO:

I am trying to get the age, gender and pregnancy status from the currently logged in user.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

My API requires age, gender and pregnancy status in order to search for data. I was hoping to prompt users to sign up or login, which will have the data for those three things stored in my DB upon signing up or logging in. Right now, I can sign in successfully from the browser console, but when I try to use req.session.currentUser to get the age, gender and pregnancy status, the currentUser is undefined and therefore I have no data to create my query string.

``` js
$(function() {
  App.searchResults = new App.Collections.SearchResultsCollection
  App.searchFormView = new App.SearchFormView({ collection: App.searchResults });
});
```
## WHAT I'VE TRIED

Originally I wrote a route to `/search`, hoping it would make a request to the `/current_user` route, get the ID and the user's data but that wasn't working. So I moved that route into the `user_router` and tried a get request from `/:id/search`, but that also didn't work. So I thought maybe I could try using a class method to get that data but I'm still having trouble making sure the user is signed in successfully when I hit the route `/search`, which needs a current user.
## QUESTION

I think I'm going about getting this information the right way, but I'm not sure why my `currentUser` is undefined. Do I need to move my routers around or combine them somehow?

:heart:
Emily

**Comment by ghost** [comment]
FYI I'm @h4w5 (PJ) !

**Comment by emilylordahl** [comment]
Whoops! @h4w5 Will said I should find you for help. Are you available?

**Comment by ghost** [comment]
Yeah, please come to 2nd floor table.

**Comment by emilylordahl** [comment]
Resolved!
